name: Python Script Workflow
on:
  schedule:
    - cron: "0 7,14,17 * * 2" # every tuesday at 7:00am and 2:00pm and 5:00pm
  push:
    branches:
      - main
jobs:
  run_script:
    runs-on: ubuntu-latest
    env:
      APPRISE_TOKEN: ${{ secrets.APPRISE_TOKEN }}
      APPRISE_TARGET: ${{ secrets.APPRISE_TARGET }}
      APP_MODE: ${{ vars.APP_MODE }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Python script
        run: python main.py
      - name: Print environment variable
        run: echo ${{ vars.APP_MODE }}
